import baseWorker from "./worker-entry-v2.js";

const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization"};

export default {async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(request.method==="POST"&&url.pathname==="/api/create-payment-intent")return createMarketplacePaymentIntent(request,env,ctx);if(request.method==="POST"&&url.pathname==="/api/stripe/webhook")return handleMarketplaceWebhook(request,env,ctx);const response=await baseWorker.fetch(request,env,ctx);if(request.method==="GET"&&isHtml(response,url))return injectMarketplaceCheckoutBridge(response);return response;}};

async function createMarketplacePaymentIntent(request,env,ctx){let body;try{body=await request.json()}catch(_){return json({error:"Invalid JSON payload"},400)}if(!env.DB)return json({error:"D1 database not configured"},500);const experienceId=String(body.experienceId||body.tourKey||"").trim().toLowerCase();if(!experienceId)return json({error:"Missing experienceId"},400);try{await ensureExperiencesTable(env);const experience=await env.DB.prepare("SELECT experience_id,title,provider_connect_account_id,status FROM experiences WHERE experience_id=? LIMIT 1").bind(experienceId).first();if(!experience)return json({error:"Experience is not configured for marketplace checkout"},409);if(String(experience.status)!=="published")return json({error:"Experience is not currently bookable"},409);const providerAccount=String(experience.provider_connect_account_id||"").trim();if(!/^acct_[A-Za-z0-9]+$/.test(providerAccount))return json({error:"Experience has no valid provider Connect account"},409);body.experienceId=experienceId;body.providerConnectAccountId=providerAccount;body.experienceName=body.experienceName||experience.title||body.tourName||"";return baseWorker.fetch(new Request(request,{method:"POST",headers:request.headers,body:JSON.stringify(body)}),env,ctx)}catch(error){console.error("FiiViu marketplace payment routing failed",error);return json({error:error?.message||"Marketplace payment routing failed"},500)}}

async function handleMarketplaceWebhook(request,env,ctx){let body;try{body=await request.text();const event=JSON.parse(body);if(event?.type==="payment_intent.succeeded"){const provider=String(event?.data?.object?.metadata?.provider_connect_account_id||"").trim();if(!/^acct_[A-Za-z0-9]+$/.test(provider))return json({error:"Payment succeeded without a valid provider Connect account"},400)}}catch(_){return json({error:"Invalid webhook payload"},400)}return baseWorker.fetch(new Request(request,{method:"POST",headers:request.headers,body}),env,ctx)}

async function injectMarketplaceCheckoutBridge(response){const html=await response.text();const bridge=`<script>(function(){var previousFetch=window.fetch.bind(window);window.fetch=function(input,init){try{var target=typeof input==='string'?input:(input&&input.url)||'';if(target.indexOf('/api/create-payment-intent')!==-1&&init&&typeof init.body==='string'){var data=JSON.parse(init.body);var key=(typeof currentTourKey!=='undefined'?String(currentTourKey||'').trim():'');if(key)data.experienceId=key.toLowerCase();init.body=JSON.stringify(data)}}catch(_){}return previousFetch(input,init)}})();</script>`;const marker="</body>";const output=html.includes(marker)?html.replace(marker,bridge+marker):html+bridge;const headers=new Headers(response.headers);headers.delete("content-length");headers.set("cache-control","no-cache");return new Response(output,{status:response.status,statusText:response.statusText,headers})}
function isHtml(response,url){if(url.pathname.startsWith("/api/"))return false;return(response.headers.get("content-type")||"").includes("text/html")}
async function ensureExperiencesTable(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS experiences (id INTEGER PRIMARY KEY AUTOINCREMENT,experience_id TEXT NOT NULL UNIQUE,provider_connect_account_id TEXT,title TEXT NOT NULL,meeting_point_name TEXT,meeting_address TEXT,meeting_city TEXT,meeting_country TEXT,meeting_instructions TEXT,arrival_minutes_before INTEGER,meeting_latitude TEXT,meeting_longitude TEXT,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','archived')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_experiences_provider ON experiences(provider_connect_account_id)").run();await env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_experiences_status ON experiences(status)").run()}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...CORS,"Content-Type":"application/json"}})}